# Generated by Django 5.2.4 on 2025-08-11 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, unique=True)),
                ('medium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artisendapi.medium')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='UserBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_img', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('bio', models.TextField(max_length=500)),
                ('business_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('business_address', models.CharField(max_length=200)),
                ('social_link', models.URLField(blank=True)),
                ('commissions_open', models.BooleanField(default=False)),
                ('skills', models.ManyToManyField(blank=True, related_name='businesses', to='artisendapi.skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMedium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_mediums', to='artisendapi.userbusiness')),
                ('medium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_business_mediums', to='artisendapi.medium')),
            ],
            options={
                'unique_together': {('business', 'medium')},
            },
        ),
        migrations.AddField(
            model_name='userbusiness',
            name='mediums',
            field=models.ManyToManyField(through='artisendapi.UserMedium', to='artisendapi.medium'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('is_business', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to='artisendapi.userbusiness')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to='artisendapi.skill')),
            ],
        ),
    ]
