# Generated by Django 5.2.4 on 2025-08-12 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisendapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='medium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='artisendapi.medium'),
        ),
    ]
