# Generated by Django 5.2.4 on 2025-08-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisendapi', '0002_alter_skill_medium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='label',
            field=models.CharField(max_length=100),
        ),
    ]
