# Generated by Django 5.2.4 on 2025-08-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisendapi', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
    ]
